#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "kiwiirc"
name = "KiwiIRC"
description.en = "Versatile web based messenger using IRC"
description.fr = "Messagerie Web polyvalente utilisant IRC"

version = "1.7.1~ynh2"

maintainers = []

[upstream]
license = "AGPL-3.0-only"
website = "https://kiwiirc.com/"
demo = "https://kiwiirc.com/nextclient"
admindoc = "https://github.com/kiwiirc/kiwiirc/wiki"
code = "https://github.com/kiwiirc/kiwiirc"
fund = "https://kiwiirc.com/donate"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false

ldap = "not_relevant"

sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    amd64.url = "https://github.com/kiwiirc/kiwiirc/releases/download/v1.7.1/kiwiirc-server_v1.7.1-2_linux_amd64.zip"
    amd64.sha256 = "25f0a5d430f59a132e99f45fd32aaab893953b713cd891f8e3e6ad417c678e13"
    arm64.url = "https://github.com/kiwiirc/kiwiirc/releases/download/v1.7.1/kiwiirc-server_v1.7.1-2_linux_arm64.zip"
    arm64.sha256 = "6b9d699f07f0b69ab41073baac52cdc8423f29ffe25e5554f56226b2a8e18efa"
    armhf.url = "https://github.com/kiwiirc/kiwiirc/releases/download/v1.7.1/kiwiirc-server_v1.7.1-2_linux_armhf.zip"
    armhf.sha256 = "38e19f0dee91a820a70f6100776cc77b5db1a6b8dafe1bcb1316cf4200edd307"
    i386.url = "https://github.com/kiwiirc/kiwiirc/releases/download/v1.7.1/kiwiirc-server_v1.7.1-2_linux_i386.zip"
    i386.sha256 = "3c1e30fbb01ddde7e23a84729dad572f81d2242e86583ca9d223843700f0ce8e"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^kiwiirc-server_.*_linux_amd64.zip$"
    autoupdate.asset.arm64 = "^kiwiirc-server_.*_linux_arm64.zip$"
    autoupdate.asset.armhf = "^kiwiirc-server_.*_linux_armhf.zip$"
    autoupdate.asset.i386 = "^kiwiirc-server_.*_linux_i386.zip$"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 7778
