location / {
  index index.html;
  root __INSTALL_DIR__/www/;
}

location /webirc/ {
  # Forward incoming requests to local webircgateway socket
  proxy_pass http://127.0.0.1:__PORT__/webirc/;
  include proxy_params_no_auth;

  # Set http version and headers
  proxy_redirect default;

  # Add X-Forwarded-* headers

  # Allow upgrades to websockets
}
